version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3093:80"
    volumes:
      - .:/var/www/html
    networks:
      - webnet
    healthcheck:
      test: ["CMD", "curl", "--silent", "--fail", "http://localhost/fpm-ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    user: "root" 

networks:
  webnet:
